networks:
  explorer-dev:

services:
  explorer:
    image: "node:20"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    restart: unless-stopped
    env_file: .env
    networks:
      - explorer-dev 
    expose:
      - "3002"
    ports: # use if it is necessary to expose the container to the host machine
      - "3002:3002"
    command: "npm start"
  xenad:
    build:
      context: ./docker/xenad
      dockerfile: ./Dockerfile
    container_name: xenad
    restart: unless-stopped
    env_file: .env
    networks:
      - explorer-dev   
    # ports:
      # - "7227:7227"
      # - "20001:20001"
      # - "20002:20002"
    volumes:
      - ./xena:/data
      - ./docker/xenad:/scripts

  cache:
    image: redis:6.2-alpine
    restart: always
    container_name: cache
    # ports:
    #   - '6379:6379'
    networks:
      - explorer-dev 
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - ./redis-data:/data

